[package]
name = "shaft-op"
version = "0.0.0"
edition = "2024"

[dependencies]
cu = { workspace = true, features = ["process", "json", "derive", "prompt-password"] }
enumset.workspace = true
reqwest = { version = "0.12.24", features = ["gzip"] }
serde = "1"
sha2 = "0.10.9"
shell-words = "1.1.1"
sysinfo = "0.37.2"
tokio = "1"

[target.'cfg(windows)'.dependencies]
win-envedit.path = "../win-envedit"
