[package]
name = "shaft-corelib"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
cu = { workspace = true, features = ["process", "json", "derive", "prompt", "toml-preserve-order", "parse-impl"] }
shaftim-build = { path = "../tools/shaftim-build", default-features = false }
enumset.workspace = true
boa_engine = "0.21.0"
fs2 = "0.4.3"
fxhash = "0.2.1"
reqwest = { version = "0.13.2", features = ["blocking", "gzip"] }
serde = "1"
sha2.workspace = true
shell-words.workspace = true
sysinfo = "0.38.1"
tokio = "1"
flate2.workspace = true
tar.workspace = true
zip.workspace = true
xz2.workspace = true

[target.'cfg(windows)'.dependencies]
win-envedit.workspace = true
winapi = { version = "0.3.9", features = ["securitybaseapi", "processthreadsapi", "impl-default"] }

[target.'cfg(unix)'.dependencies]
libc.workspace = true
