[package]
name = "shaft-corelib"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
boa_engine = "0.21.0"
cu = { workspace = true, features = ["process", "json", "derive", "prompt"] }
enumset.workspace = true
fs2 = "0.4.3"
fxhash = "0.2.1"
reqwest = { version = "0.13.1", features = ["blocking", "gzip"] }
serde = "1"
sha2 = "0.10.9"
shell-words = "1.1.1"
sysinfo = "0.37.2"
tokio = "1"
flate2 = "1.1.8"
tar = "0.4.44"

[target.'cfg(windows)'.dependencies]
win-envedit = { version = "0.1.2", git = "https://github.com/Pistonite/shellutils", branch = "main" }
winapi = { version = "0.3.9", features = ["securitybaseapi", "processthreadsapi", "impl-default"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2.180"

[build-dependencies]
cu = { workspace = true, features = [
    "fs"
] }
flate2 = "1.1.8"
ignore = "0.4.25"
tar = "0.4.44"
