[workspace]
resolver = "2"
members = [
    "packages/procname-checker",
    "packages/shaft-build",
    "packages/shaft-cli",
    "packages/shaft-corelib",
    "packages/shaft-registry",
]

[workspace.dependencies.cu]
package = "pistonite-cu"
# path = "../cu/packages/copper"
version = "0.6.8"

[workspace.dependencies.pm]
package = "pistonite-pm"
# path = "../cu/packages/promethium"
version = "0.2.2"
default-features = false

[workspace.dependencies.corelib]
package = "shaft-corelib"
path = "./packages/shaft-corelib"

[workspace.dependencies]
enum-map = "2.7.3"
enumset = "1.1.10"
itertools = "0.14.0"
