[workspace]
resolver = "2"
members = [
    "packages/shaft-build",
    "packages/shaft-cli",
    "packages/shaft-op",
    "packages/shaft-registry",
]

[workspace.dependencies.cu]
package = "pistonite-cu"
version = "0.6.0"

[workspace.dependencies.pm]
package = "pistonite-pm"
version = "0.1.4"
default-features = false

[workspace.dependencies.op]
package = "shaft-op"
path = "./packages/shaft-op"

[workspace.dependencies]
enum-map = "2.7.3"
enumset = "1.1.10"
itertools = "0.14.0"
