[workspace]
resolver = "2"
members = [
    "packages/procname-checker",
    "packages/corelib",
    "packages/registry-build",
    "packages/cli",
    "packages/registry",
]

[workspace.dependencies.cu]
package = "pistonite-cu"
version = "0.7.1"
# path = "../cu/packages/copper"

[workspace.dependencies.pm]
package = "pistonite-pm"
version = "0.2.4"
default-features = false
# path = "../cu/packages/promethium"

[workspace.dependencies.corelib]
package = "shaft-corelib"
path = "./packages/corelib"

[workspace.dependencies]
enum-map = "2.7.3"
enumset = "1.1.10"
itertools = "0.14.0"
