[workspace]
resolver = "2"
members = [
    "packages/shaft-build",
    "packages/shaft-cli",
    "packages/shaft-op",
    "packages/shaft-registry",
    "packages/win-envedit",
    "packages/win-pathedit",
]

[workspace.dependencies.cu]
package = "pistonite-cu"
# path = "../cu/packages/copper"
version = "0.6.5"

[workspace.dependencies.pm]
package = "pistonite-pm"
# path = "../cu/packages/promethium"
version = "0.2.1"
default-features = false

[workspace.dependencies.op]
package = "shaft-op"
path = "./packages/shaft-op"

[workspace.dependencies]
enum-map = "2.7.3"
enumset = "1.1.10"
itertools = "0.14.0"
