[[section]]
comment = """
List of GNU executables that have parity
Linux GNU       Windows LLVM-minGW
-------------------------------------------------
gcc:            llvm-mingw:
  c++             c++.exe
  c99             c99.exe
  cc              cc.exe
  gcc             gcc.exe
  g++             g++.exe
binutils:
  addr2line       addr2line.exe
  ar              ar.exe 
  c++filt         *links to llvm-cxxfilt.exe (from LLVM-minGW)
  ld              *bash-wrapped ld
  nm              nm.exe
  objcopy         objcopy.exe
  objdump         *bash-wrapped objdump
  ranlib          ranlib.exe
  readelf         readelf.exe
  size            size.exe
  strings         strings.exe
  strip           strip.exe
make:
  make            *links to mingw32-make.exe

List of CLANG/LLVM executables that are both on Linux and Windows
-------------------------------------------------
L means this is only in Linux
! means this is in both Linux and Windows, but will not be made
  in PATH in Windows
  Of course, the Windows executable will have an extra .exe extension
W means only on Windows
-------------------------------------------------
clang:
  amdgpu-arch
  analyze-build             (Windows: python-wrapped)
  c-index-test
  clang
  clang++
L clang-21
  clang-apply-replacements
  clang-change-namespace
  clang-check
  clang-cl
  clang-cpp
  clang-doc
  clang-extdef-mapping
  clang-format
  clang-include-cleaner
  clang-include-fixer
  clang-installapi
  clang-linker-wrapper
  clang-move
  clang-nvlink-wrapper
  clang-offload-bundler
  clang-offload-packager
  clang-query
  clang-refactor
  clang-reorder-fields
  clang-repl
  clang-scan-deps
  clang-sycl-linker
W clang-tblgen.exe
  clang-tidy
  clangd
  diagtool
  find-all-symbols
  git-clang-format           (Windows: python-wrapped)
  hmaptool                   (Windows: python-wrapped)
  intercept-build            (Windows: python-wrapped)
  modularize
  nvptx-arch
  offload-arch
  pp-trace
  run-clang-tidy             (Windows: python-wrapped)
! scan-build
! scan-build-py
! scan-view
llvm:
  bugpoint
L count
  dsymutil
L lit
L llc
W lld.exe
L lli
L lli-child-target
  llvm-addr2line
  llvm-ar
  llvm-as
  llvm-bcanalyzer
  llvm-bitcode-strip
  llvm-c-test
  llvm-cat
  llvm-cfi-verify
  llvm-cgdata
  llvm-config
  llvm-cov
  llvm-ctxprof-util
  llvm-cvtres
  llvm-cxxdump
  llvm-cxxfilt
  llvm-cxxmap
  llvm-debuginfo-analyzer
  llvm-debuginfod
  llvm-debuginfod-find
  llvm-diff
  llvm-dis
  llvm-dlltool
  llvm-dwarfdump
  llvm-dwarfutil
  llvm-dwp
W llvm-exegesis
  llvm-extract
  llvm-gsymutil
  llvm-ifs
  llvm-install-name-tool
  llvm-jitlink
  llvm-jitlink-executor
  llvm-lib
  llvm-libtool-darwin
  llvm-link
  llvm-lipo
  llvm-lto
  llvm-lto2
  llvm-mc
  llvm-mca
  llvm-ml
  llvm-ml64
  llvm-modextract
  llvm-mt
  llvm-nm
  llvm-objcopy
  llvm-objdump
  llvm-opt-report
  llvm-otool
  llvm-pdbutil
  llvm-profdata
  llvm-profgen
  llvm-ranlib
  llvm-rc
  llvm-readelf
  llvm-readobj
  llvm-readtapi
  llvm-reduce
  llvm-remarkutil
  llvm-rtdyld
  llvm-sim
  llvm-size
  llvm-split
  llvm-stress
  llvm-strings
  llvm-strip
  llvm-symbolizer
  llvm-tblgen
L llvm-test-mustache-spec
  llvm-tli-checker
  llvm-undname
  llvm-windres
  llvm-xray
L not
L obj2yaml
  opt
  reduce-chunk-list
  sancov
  sanstats
L split-file
  verify-uselistorder
L yaml-bench
L yaml2obj
W wasm-ld.exe
lldb:
  lldb
  lldb-argdumper
  lldb-dap
  lldb-instr
  lldb-server

"""

[[section]]
comment = "Windows-specific configuration"
key = ["windows"]
children = [
    {
        comment = """
Extra files in LLVM-minGW/bin to make available in PATH.
This has effect regardless of llvm-target.
However, it cannot conflict with whatever is already available based on other configs
""",
        key = ["gnu", "extra-links"],
        value = [],
    },
    {
        comment = """
Extra files in LLVM-minGW/bin to make available in PATH as a shim executable.
The shim executable will prepend LLVM-minGW/bin to PATH, so that nested invocations
will not go through the shim.
This has effect regardless of llvm-target.
However, it cannot conflict with whatever is already available based on other configs
""",
        key = ["gnu", "extra-shims"],
        value = [],
    },
    {
        comment = """
Extra files in LLVM-minGW/bin to make available in PATH as a bash-wrapped executable
The shim executable will prepend LLVM-minGW/bin to PATH, so that nested invocations
will not go through the shim.
This has effect regardless of llvm-target.
However, it cannot conflict with whatever is already available based on other configs
""",
        key = ["gnu", "extra-bash-wrapped"],
        value = [],
    },
    {
        comment = """
Extra files in LLVM-minGW/bin to make available in PATH as a python-wrapped executable
The shim executable will prepend LLVM-minGW/bin to PATH, so that nested invocations
will not go through the shim.
This has effect regardless of llvm-target.
However, it cannot conflict with whatever is already available based on other configs
""",
        key = ["gnu", "extra-python-wrapped"],
        value = [],
    },
    {
        comment = """
Extra files in clang-LLVM/bin to make available in PATH.
This has effect regardless of llvm-target.
However, it cannot conflict with whatever is already available based on other configs
""",
        key = ["msvc", "extra-links"],
        value = [],
    },
    {
        comment = """
Extra files in clang-LLVM/bin to make available in PATH as a shim executable.
The shim executable will prepend LLVM-minGW/bin to PATH, so that nested invocations
will not go through the shim.
This has effect regardless of llvm-target.
However, it cannot conflict with whatever is already available based on other configs
""",
        key = ["msvc", "extra-shims"],
        value = [],
    },
    {
        comment = """
Extra files in clang-LLVM/bin to make available in PATH as a bash-wrapped executable
The shim executable will prepend LLVM-minGW/bin to PATH, so that nested invocations
will not go through the shim.
This has effect regardless of llvm-target.
However, it cannot conflict with whatever is already available based on other configs
""",
        key = ["msvc", "extra-bash-wrapped"],
        value = [],
    },
    {
        comment = """
Extra files in clang-LLVM/bin to make available in PATH as a python-wrapped executable
The shim executable will prepend LLVM-minGW/bin to PATH, so that nested invocations
will not go through the shim.
This has effect regardless of llvm-target.
However, it cannot conflict with whatever is already available based on other configs
""",
        key = ["msvc", "extra-python-wrapped"],
        value = [],
    },
]
