[package]
name = "shaft-build"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
cu = { workspace = true, features = ["fs", "json", "derive"] }
pm = { workspace = true, features = ["full"] }
itertools.workspace = true
