[package]
name = "shaft-cli"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
cu = { workspace = true, features = ["cli", "print", "prompt", "fs", "derive", "coroutine-heavy", "json"] }
op.workspace = true
serde = "1"

[[bin]]
name = "shaft"
path = "src/main.rs"

