[package]
name = "shaft-cli"
version = "0.2.5"
edition = "2024"
publish = false
repository = "https://github.com/Pistonite/shaft"

[dependencies]
cu = { workspace = true, features = [
    "cli",
    "prompt",
    "fs",
    "derive",
    "json",
    "toml",
] }
corelib = { package = "shaft-corelib", path = "../corelib" }
registry = { package = "shaft-registry", path = "../registry" }
serde = "1"
enumset.workspace = true
enum-map.workspace = true
viopen.workspace = true
itertools.workspace = true

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"

[[bin]]
name = "shaft"
path = "src/main.rs"

[package.metadata.binstall.signing]
algorithm = "minisign"
pubkey = "RWThJQKJaXayoZBe0YV5LV4KFkQwcqQ6Fg9dJBz18JnpHGdf/cHUyKs+"
