[package]
name = "shaft-registry"
description = "shaft registry for packages"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
cu = { workspace = true, features = ["print", "process", "toml"] }
enum-map.workspace = true
enumset.workspace = true
corelib.workspace = true
serde = "1"
phf = { version = "0.13.1", features = ["macros"] }

[build-dependencies]
cu = { workspace = true, features = ["toml"] }
shaft-registry-build = { path = "../registry-build" }
