[package]
name = "shaft-registry"
description = "shaft registry for packages"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
cu = { workspace = true, features = ["print", "process", "toml"] }
corelib = { package = "shaft-corelib", path = "../corelib" }
enum-map.workspace = true
enumset.workspace = true
serde = "1"
phf = { version = "0.13.1", features = ["macros"] }
shaftim-build = { path = "../tools/shaftim-build", default-features = false }
