[_7z]
REPO = "https://github.com/ip7z/7zip"
VERSION = "25.01"
'cfg(target_arch="aarch64")'.SHA = "6365c7c44e217b9c1009e065daf9f9aa37454e64315b4aaa263f7f8f060755dc"
'cfg(target_arch="x86_64")'.SHA = "78afa2a1c773caf3cf7edf62f857d2a8a5da55fb0fff5da416074c0d28b2b55f"

[pwsh]
# using preview version to enable tilde (~) expansion
REPO = "https://github.com/PowerShell/PowerShell"
VERSION = "7.6.0-preview.6"
'cfg(target_arch="aarch64")'.SHA = '36dc90e7f0e7870b0970c9a58790de4de4217e65acafaf790e87b7c97d93649f'
'cfg(target_arch="x86_64")'.SHA = '481ce45bd9ebfab9a5b254a35f145fb6259bd452ae67d92ab1d231b6367987d9'

[cargo_binstall]
VERSION = "1.17.4"

[coreutils]
ALIAS_VERSION = "6"
eza.VERSION = "0.23.4"
uutils.VERSION = "0.5.0"
zip.VERSION = "3.0"
unzip.VERSION = "6.0"
tar.VERSION = "1.35"
which.VERSION = "2.23"
bash.VERSION = "5.3.9"
bash_cmp.VERSION = "2.17.0"

[shellutils]
ALIAS_VERSION = "4"
REPO = "https://github.com/Pistonite/shellutils"
COMMIT = "331ee9d19e26ed82ca42b31513a042381ca8db3a"
which.VERSION = "0.1.3"
viopen.VERSION = "0.1.3"
vipath.VERSION = "0.1.5"
n.VERSION = "0.1.1"
wsclip.VERSION = "0.1.5"

[git]
'cfg(windows)'.ALIAS_VERSION = "1"
'cfg(windows)'.VERSION = "2.52.0"
'cfg(target_os="linux")'.VERSION = "2.52.0"
delta.VERSION = "0.18.2"
CFG_VERSION = "1"

[perl]
'cfg(target_os="linux")'.VERSION = "5.42.0"

[curl]
'cfg(target_os="linux")'.VERSION = "8.18.0"
# Windows ships with curl.exe

[wget]
'cfg(target_os="linux")'.VERSION = "1.25.0"
'cfg(windows)'.REPO = "https://github.com/lifenjoiner/wget-for-windows"
'cfg(windows)'.VERSION = "1.25.0"
'cfg(windows)'.URL = "https://github.com/lifenjoiner/wget-for-windows/releases/download/v1.25.0.230-a13d0/wget-ucrt64-xp-openssl-lite_v1.25.0.230-a13d0_e2f4498e19fa63184014e3b9d2f071bbc1c6217b.7z"
'cfg(windows)'.SHA = "fd60911ec2d94857e55e574521e8cb247ff852b58a34348a829f7cd98a2530e7"

[fzf]
REPO = "https://github.com/junegunn/fzf"
VERSION = "0.67.0"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "4a39934cc8f670048a7fb21dde09096adcbda7adc676010dd9cec90780d3b9df"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "cad95326ed416d14226a03425513b049f5bc9a41f30a355e5fe204a29e666867"

[jq]
REPO = "https://github.com/jqlang/jq"
VERSION = "1.8.1"
'cfg(windows)'.SHA = "23cb60a1354eed6bcc8d9b9735e8c7b388cd1fdcb75726b93bc299ef22dd9334"

[task]
REPO = "https://github.com/go-task/task"
VERSION = "3.48.0"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "10409f9401bcac6a0b5a7928d0216f1818140ba4b685509694fdd4b580fa0f97"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "d6dd072d8b1c8131626cacd96af5edbc54470c437f747ec87f3fab32a15b3c74"
'cfg(target_os="linux")'.SHA = "f4bfc4eef1b2557b262f3cc0a79976a421885cb7b9e71cfe75568a2ebe4d7ae5"

[bat]
VERSION = "0.26.1"

[dust]
VERSION = "1.2.4"

[fd]
VERSION = "10.3.0"

[websocat]
VERSION = "1.14.1"

[zoxide]
VERSION = "0.9.8"

[hack_font]
REPO = "https://github.com/ryanoasis/nerd-fonts"
VERSION_PACMAN = "3.4.0-2"
VERSION = "3.4.0"
SHA = "8ca33a60c791392d872b80d26c42f2bfa914a480f9eb2d7516d9f84373c36897"

[terminal]
'cfg(windows)'.CONFIG_VERSION = "7"

[volta]
REPO = "https://github.com/volta-cli/volta"
VERSION = "2.0.2"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "a996918b7a7bf2af9ceffce005208943f4eeaf779757ca73f5dfaa91a0072ad7"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "d7678a485e2fc9b1a3f7e9da256d8b88a97d7e4c45e63701c4874f6c2a587e0f"
'cfg(target_os="linux")'.SHA = "6cec054c911fb925b629a09455775af6e95dc0f5694a4c28b63979ab9ef18037"
ALIAS_VERSION = "1"
pnpm.REPO = "https://github.com/pnpm/pnpm"
pnpm.VERSION = "10.28.2"
node.VERSION = "24"
yarn.VERSION = "4"

