[core]
# Bumping this version will re-configure all installed packages
CONFIG_VERSION = "2"

[_7z]
REPO = "https://github.com/ip7z/7zip"
VERSION = "25.01"
'cfg(target_arch="aarch64")'.SHA = "6365c7c44e217b9c1009e065daf9f9aa37454e64315b4aaa263f7f8f060755dc"
'cfg(target_arch="x86_64")'.SHA = "78afa2a1c773caf3cf7edf62f857d2a8a5da55fb0fff5da416074c0d28b2b55f"

[pwsh]
# using preview version to enable tilde (~) expansion
REPO = "https://github.com/PowerShell/PowerShell"
VERSION = "7.6.0-preview.6"
'cfg(target_arch="aarch64")'.SHA = '36dc90e7f0e7870b0970c9a58790de4de4217e65acafaf790e87b7c97d93649f'
'cfg(target_arch="x86_64")'.SHA = '481ce45bd9ebfab9a5b254a35f145fb6259bd452ae67d92ab1d231b6367987d9'

[cargo_binstall]
VERSION = "1.17.4"

[coreutils]
ALIAS_VERSION = "8"
eza.VERSION = "0.23.4"
uutils.VERSION = "0.6.0"
zip.VERSION = "3.0"
unzip.VERSION = "6.0"
tar.VERSION = "1.35"
which.VERSION = "2.23"
bash.VERSION = "5.3.9"
bash_cmp.VERSION = "2.17.0"

[shellutils]
ALIAS_VERSION = "6"
REPO = "https://github.com/Pistonite/shellutils"
COMMIT = "b714fd6b2ed7308e1ed9e5dae989667a0f7a7164"
which.VERSION = "0.1.3"
viopen.VERSION = "0.1.4"
vipath.VERSION = "0.1.6"
n.VERSION = "0.1.1"
wsclip.VERSION = "0.1.6"

[git]
'cfg(windows)'.ALIAS_VERSION = "1"
'cfg(windows)'.VERSION = "2.52.0"
'cfg(target_os="linux")'.VERSION = "2.53.0"
delta.VERSION = "0.18.2"
CFG_VERSION = "2"

[perl]
'cfg(target_os="linux")'.VERSION = "5.42.0"

[curl]
'cfg(target_os="linux")'.VERSION = "8.18.0"
# Windows ships with curl.exe

[wget]
'cfg(target_os="linux")'.VERSION = "1.25.0"
'cfg(windows)'.REPO = "https://github.com/lifenjoiner/wget-for-windows"
'cfg(windows)'.VERSION = "1.25.0"
'cfg(windows)'.URL = "https://github.com/lifenjoiner/wget-for-windows/releases/download/v1.25.0.230-a13d0/wget-ucrt64-xp-openssl-lite_v1.25.0.230-a13d0_e2f4498e19fa63184014e3b9d2f071bbc1c6217b.7z"
'cfg(windows)'.SHA = "fd60911ec2d94857e55e574521e8cb247ff852b58a34348a829f7cd98a2530e7"

[fzf]
REPO = "https://github.com/junegunn/fzf"
VERSION = "0.67.0"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "4a39934cc8f670048a7fb21dde09096adcbda7adc676010dd9cec90780d3b9df"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "cad95326ed416d14226a03425513b049f5bc9a41f30a355e5fe204a29e666867"

[jq]
REPO = "https://github.com/jqlang/jq"
VERSION = "1.8.1"
'cfg(windows)'.SHA = "23cb60a1354eed6bcc8d9b9735e8c7b388cd1fdcb75726b93bc299ef22dd9334"

[task]
REPO = "https://github.com/go-task/task"
VERSION = "3.48.0"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "10409f9401bcac6a0b5a7928d0216f1818140ba4b685509694fdd4b580fa0f97"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "d6dd072d8b1c8131626cacd96af5edbc54470c437f747ec87f3fab32a15b3c74"
'cfg(target_os="linux")'.SHA = "f4bfc4eef1b2557b262f3cc0a79976a421885cb7b9e71cfe75568a2ebe4d7ae5"

[bat]
VERSION = "0.26.1"

[dust]
VERSION = "1.2.4"

[fd]
VERSION = "10.3.0"

[rg]
VERSION = "15.1.0"

[websocat]
VERSION = "1.14.1"

[zoxide]
VERSION = "0.9.9"

[hack_font]
REPO = "https://github.com/ryanoasis/nerd-fonts"
VERSION_PACMAN = "3.4.0-2"
VERSION = "3.4.0"
SHA = "8ca33a60c791392d872b80d26c42f2bfa914a480f9eb2d7516d9f84373c36897"

[terminal]
'cfg(windows)'.CONFIG_VERSION = "8"
clink.REPO = "https://github.com/chrisant996/clink"
clink.VERSION = "1.9.11"
clink.SHA = "61aacd20b126274a4a6bb1c1662e6fd6d6ba64ec86b7ed61df93cd4e631fa702"
clink.URL = "https://github.com/chrisant996/clink/releases/download/v1.9.11/clink.1.9.11.760de7.zip"
clink.WRAPPER_VERSION = "2"

[volta]
REPO = "https://github.com/volta-cli/volta"
VERSION = "2.0.2"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "a996918b7a7bf2af9ceffce005208943f4eeaf779757ca73f5dfaa91a0072ad7"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "d7678a485e2fc9b1a3f7e9da256d8b88a97d7e4c45e63701c4874f6c2a587e0f"
'cfg(target_os="linux")'.SHA = "6cec054c911fb925b629a09455775af6e95dc0f5694a4c28b63979ab9ef18037"
ALIAS_VERSION = "1"
pnpm.REPO = "https://github.com/pnpm/pnpm"
pnpm.VERSION = "10.29.1"
node.VERSION = "24"
yarn.VERSION = "4"

[uv]
ALIAS_VERSION = "1"
VERSION = "0.10.0"

[gnucc]
gcc.VERSION = "15.2.1"
binutils.VERSION = "2.45.1"
gdb.VERSION = "17.1"

[clang]
REPO = "https://github.com/llvm/llvm-project"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "f214b1226d8de005b5f691dd29d9dfea2b49e22d0de445429916173dbb626f7f"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "749d22f565fcd5718dbed06512572d0e5353b502c03fe1f7f17ee8b8aca21a47"
'cfg(windows)'.LLVM_VERSION = "21.1.8"
'cfg(target_os="linux")'.LLVM_VERSION = "21.1.6"

[llvm_mingw]
REPO = "https://github.com/mstorsjo/llvm-mingw"
TAG = "20251216"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "60c06bd255feb2ef1eb6fce7ee6b307d8f78ee6639660f49861c7c10a8a86164"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "2d96a4b758f7f8deaec5065833fe025aa53cfc5f704d0524002510984da0ccf4"
'cfg(windows)'.LLVM_VERSION = "21.1.8"


[cmake]
# this is official
REPO = "https://github.com/Kitware/CMake"
'cfg(windows)'.VERSION = "4.2.3"
'cfg(target_os="linux")'.VERSION = "4.2.3"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "751b206b1cf65151b72c525d26267c1d9beebf8fafc365ae00286571d9fd3ed9"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "eb4ebf5155dbb05436d675706b2a08189430df58904257ae5e91bcba4c86933c"

[ninja]
REPO = "https://github.com/ninja-build/ninja"
'cfg(windows)'.VERSION = "1.13.2"
'cfg(target_os="linux")'.VERSION = "1.13.2"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "e52f0bdef9dfb1003229dbd6508a508c4073fd017247002adc66e5e806cb0391"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "07fc8261b42b20e71d1720b39068c2e14ffcee6396b76fb7a795fb460b78dc65"

[starship]
VERSION = "1.24.2"
CFG_VERSION = "9"

[nvim]
REPO = "https://github.com/neovim/neovim"
VERSION = "0.11.6"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "67a4e1da1f0d99e71c5e7b2dfd95f8c34721bd8c139eec99bb3e9034c2766301"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "90fc6d7cdf3d3388737caab1e2c554aa24b468f3a5cc38ef63857ddf1103513c"
'cfg(target_os="linux")'.SHA = "2fc90b962327f73a78afbfb8203fd19db8db9cdf4ee5e2bef84704339add89cc"
NVIM_CFG = "5"

[tree_sitter]
VERSION = "0.26.5"
REPO = "https://github.com/tree-sitter/tree-sitter"
'cfg(all(windows,target_arch="aarch64"))'.SHA = "493701ef90ec27bec29a9b53f4d6a49b753d79d534d07351f85a2af4b71ac9dc"
'cfg(all(windows,target_arch="x86_64"))'.SHA = "0adfa6a81fd94d3a8eda9d9c89333bf1263bc112c7797dc90bea80b519fe2181"
'cfg(target_os="linux")'.SHA = "d38d9a22ef398489e1eb291b2dea41467487020fe8280c2311dbbad9ba663a34"
