[package]
name = "win-pathedit"
version = "0.1.0"
edition = "2024"

[dependencies]
cu = { workspace = true, features = ["cli", "derive", "print", "process"] }
win-envedit.path = "../win-envedit"

[[bin]]
path = "src/main.rs"
name = "vipath"
